# action.yml
name: "Hermes Summarize"
description: "Test Hermes"
inputs:
  gemini_token: # id of input
    description: "gemini_token"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
