on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Hermes
        id: hello
        uses: ElecTwix/hermes@0cafdf630fe99e918c90764847347f46b43e1453
        with:
          who-to-greet: "Hello 123"
