on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Hermes
        id: hello
        env:
          API_KEY_SECRET: ${{ secrets.ApiKeySecret }}
        uses: ElecTwix/hermes@657afc836db7e651dbfc2726e77e21da8a088a98
        with:
          who-to-greet: "Hello 123"
