on:
  pull_request:

jobs:
  hermes-summarize:
    runs-on: ubuntu-latest
    name: Hermes summarize
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Hermes
        id: hello
        env:
          GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

          GITHUB_REPO_OWNER: ${{github.event.pull_request.head.repo.owner.login}}
          GITHUB_REPO_NAME: ${{github.event.pull_request.head.repo.name}}

          GEMINI_KEY: ${{ secrets.key }}
          PR_GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        uses: ElecTwix/hermes@24b10c2c1dc17568fb660dc4801fa6bf3ebccf95
