on:
  pull_request:

jobs:
  hermes-summarize:
    runs-on: ubuntu-latest
    name: Hermes summarize
    steps:
      - uses: actions/checkout@v4
      - name: Hermes
        id: hello
        env:
          GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

          GITHUB_REPO_OWNER: ${{github.event.pull_request.head.repo.owner.login}}
          GITHUB_REPO_NAME: ${{github.event.pull_request.head.repo.name}}

          API_KEY_SECRET: ${{ secrets.ApiKeySecret }}
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
        uses: ElecTwix/hermes@4f5fa7523bc10b89618a5113bf5e4a017ed2e9de
