on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Hermes
        id: hello
        uses: ElecTwix/hermes@ce45a5e564a26b6f8e25e2b3a56376292ccbf662
        with:
          who-to-greet: "Hello 123"
